name: Build/Test/Deploy develop

# Controls when the action will run. Triggers the workflow on push or pull request.

on:
  push:
    branches: [develop]
  workflow_dispatch:
    branches: [develop]
  pull_request:
    branches: [develop, master, 'feature/*']

env:
  APP_DIRECTORY: dist
  REMOTE_NAME: origin
  BASE_BRANCH: ${{ github.base_ref }}
  HEAD: ${{ github.event.pull_request.head.ref }}

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AFFECTED_COMMAND_PARAMS: --base=$REMOTE_NAME/$ORIGIN_BASE_BRANCH --head=$HEAD

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 $REMOTE_NAME $GITHUB_BASE_REF

      - name: Echo
        run: echo $GITHUB_BASE_REF
      - name: Echo2
        run: echo $GITHUB_HEAD_REF
      - name: Echo3
        run: git fetch --all

      - name: Use Node.js v12.14
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run affected-lint -- --base=$REMOTE_NAME/$GITHUB_BASE_REF --head=$GITHUB_HEAD_REF

      - name: Build
        run: npm run nx affected:build

      - name: Test
        run: npm run nx affected:lint


      - name: Upload app artifacts
        uses: actions/upload-artifact@master
        with:
          name: app
          path: ${{ env.APP_DIRECTORY }}
