name: Validate/Build/Deploy Preview

# Controls when the action will run. Triggers the workflow on push or pull request.
# Link to default env variables that are provided by GitHub - https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

on:
  pull_request:
    branches: [develop, master, 'feature/*']

env:
  APP_DIRECTORY: dist
  BUILD_ALL: ${{ github.event.inputs.logLevel }}
  NX_HEAD: ${{ github.event.after }}
  NX_BASE: ${{ github.event.before }}

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 $REMOTE_NAME $GITHUB_BASE_REF

      - name: Use Node.js v12.14
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run affected-lint -- --base=$REMOTE_NAME/$GITHUB_BASE_REF --head=$GITHUB_HEAD_REF

      - name: Test
        run: npm run affected-test -- --base=$REMOTE_NAME/$GITHUB_BASE_REF --head=$GITHUB_HEAD_REF

  deploy_previews:
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    env:
      APP_DIRECTORY: app-output
      GCS_BUCKET: ${{ secrets.GCS_BUCKET_DEVELOP }}
      GCS_PROJECT: ${{ secrets.GCS_PROJECT_DEVELOP }}
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEVELOP }}
      SHELL_APP_NAME: shell
      DEPLOY_PATH: apps

    steps:
      # - name: Start deployment
      #   uses: bobheadxi/deployments@v0.5.2
      #   id: deployment
      #   with:
      #     step: start
      #     token: ${{ secrets.GITHUB }}
      #     env: development

      - uses: actions/checkout@v2
        name: Checkout Base
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Use Node.js v12.14
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3

      - name: Build app
        run: npx nx affected --target=build --configuration=develop --parallel --max-parallel=3 --all

      - name: Deploy previews
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: hosting-deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANECDOTES_DEV }}'
          projectId: anecdotes-dev
          expires: 5d
      
      # - name: Update deployment status
      #   uses: bobheadxi/deployments@v0.5.2
      #   if: always()
      #   with:
      #     step: finish
      #     token: ${{ secrets.GITHUB }}
      #     status: ${{ job.status }}
      #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      #     env_url: https://platform-dev.anecdotes.ai